language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - gLei1776@gmail.com
    on_success: always
    on_failure: never

    recipients:
      - ypc231@nyu.edu
    on_success: always
    on_failure: always  
